### ISSUE TITLE
A8 Instrument list

### ISSUE THREAD

**Issue by desimonenm** [nccoos/platforms#53]
- [x] Teledyne ADCP (sn#23455)
- [x] SBE 37 SMP CTD (sn#37SM26360-1986)
- [x] Edgetech Transponder release x2 (sn#45216,45217)
- [x] Teledyne 4 cell battery pack (sn#)
- [x] teledyne transponder (sn#)
- [x] mooring systems inc paltform(sn#Q-2138-15)
- [x] anchor
