### ISSUE TITLE
A6 Instrument list

### ISSUE THREAD

**Issue by desimonenm** [nccoos/platforms#54]
- [x] Teledyne ADCP (sn#19461)
- [x] SBE 37 SMP CTD (sn#37-13415)
- [x] Edgetech Transponder release x2 (sn#51059,51060)
- [x] Teledyne ADCP (4) Battery pack (sn#75536)
- [x] Teledyne UAT-376EL transponder (sn#58923)
- [x] Aural hydrophone (sn#MTEAU00225LF)
- [x] mooring systems inc paltform(H-TRBM-65)
- [x] anchor

**Comment by desimonenm** [comment]
final instrument list for A6 pod
